interpreter done
Krock21rus/bash pull request #1
Opened 2020-02-02 04:36 UTC by Krock21rus

С самого начала делал всё в ветке master. Поэтому история разработки хранится в самых первых коммитах, а тут лишь результирующий

2020-02-10 16:35 UTC, yurii-litvinov requested changes
```
x=1
echo "'$x'"
'$x'
```
--- тут ожидалось, что подстановка всё-таки будет выполнена, одинарные кавычки тут просто символы строки.

И на ввод вида `cat cli.py |` лучше ругаться. Сейчас ничего не происходит просто.

Насчёт отсутствия классов ситуация двоякая --- с одной стороны, наш курс ориентирован на ООП прежде всего, и мы пару занятий уже потратили на то, как правильно выделять абстракции. С другой стороны, ну да, файл можно примерно считать классом, в Питоне так принято. Так что будем считать, что с архитектурой всё ок (да на самом деле и то, что получилось, не сильно отличается от более объектно-ориентированных решений). Поправьте мелкие замечания по функциональности и будет зачтена.

2020-02-10 16:35 UTC, yurii-litvinov commented on bash_builtins.py
> +    parser.add_argument("FILE", help='path to file')
Не-а, аргумент FILE опционален. Если его не передали, то cat просто выдаёт в выходной поток содержимое входного потока.

2020-02-10 16:35 UTC, yurii-litvinov commented on bash_builtins.py
> +        fout.write(str(len(lines)) + " " + str(words_count) + " " + str(file_size))
Как-то копипастно. Не так уж эти случаи и различаются

2020-02-10 16:35 UTC, yurii-litvinov commented on bash_builtins.py
> +    os.kill(os.getpid(), signal.SIGTERM)
Брутально. Лучше это делать как-то менее низкоуровнево, проинформировав основной цикл. А то вот захочу я встроить Ваш шелл в свою гигантскую информационную систему, вызову его REPL как функцию, там пользователь напишет exit --- и прибьёт весь процесс, а не только шелл.

2020-02-10 16:35 UTC, yurii-litvinov commented on interprete.py
> +    interprete tokens as bash command(maybe with pipes).
interpret же

2020-02-10 16:35 UTC, yurii-litvinov commented on unittests.py
> +# }
Это лучше убрать или сделать нормальным комментарием --- мол, поддерживаются такие-то команды

2020-02-10 16:35 UTC, yurii-litvinov commented on bash_builtins.py
> +    fout.write(' '.join(vars(parsed_args).get("argument")))
echo ещё должна перевод строки добавлять по идее. Я понимаю, что строгое следование семантике bash-а не требовалось, но с переводом строки реально удобнее.

То же касается остальных команд. Не очень удобно вводить следующую команду на той же строке, где был вывод предыдущей.

2020-02-10 17:12 UTC, Krock21rus commented on bash_builtins.py
> +    os.kill(os.getpid(), signal.SIGTERM)
Тогда будет связь из bash_builtins в cli, что тоже плохо. Есть более элегантные решения?
Ловить в cli.py тоже не очень, ввиду 'cat cli.py | exit | cat cli.py'

2020-02-10 17:19 UTC, Krock21rus commented on bash_builtins.py
> +    fout.write(' '.join(vars(parsed_args).get("argument")))
Я сначала добавлял '\n', а потом понял, что это платформозависимо(на windows мб нужно '\r\n'), и в тестах придётся добавлять какие-то константы.
Поэтому, чтобы не поддерживать разные платформы, убрал

2020-02-10 17:25 UTC, Krock21rus commented on bash_builtins.py
> +        fout.write(str(len(lines)) + " " + str(words_count) + " " + str(file_size))
Да, я исправил это, но почему-то не закоммитилось

2020-02-10 17:36 UTC, Krock21rus commented on bash_builtins.py
> +    fout.write(' '.join(vars(parsed_args).get("argument")))
Решил с константой os.linesep. Не очень понятно, что лучше. Теперь про неё во всех юнит тестах вспоминать приходится

2020-02-10 17:46 UTC, Krock21rus commented on bash_builtins.py
> +        fout.write(str(len(lines)) + " " + str(words_count) + " " + str(file_size))
Вернее закоммитилось, но в ветку grep, т.к. после дедлайна это делал

2020-02-10 18:50 UTC, yurii-litvinov commented on bash_builtins.py
> +    os.kill(os.getpid(), signal.SIGTERM)
Типичное решение --- это сделать флаг "надо выйти", положить его куда-то в глобально видимое место (его можно понимать как часть окружения) и проверять его в основном цикле/пайпах.

2020-02-12 00:17 UTC, Krock21rus commented on bash_builtins.py
> +    os.kill(os.getpid(), signal.SIGTERM)
Добавил globals.py, и теперь bash_builtins и cli связаны с ним

2020-03-14 19:48 UTC, yurii-litvinov approved these changes
Вот теперь всё хорошо. Зачтена.

2020-03-14 19:48 UTC, yurii-litvinov commented on interpret.py
> +        raise SyntaxError("Empty command with pipes is restricted")
Скорее, "prohibited", "restricted" --- это "ограничен" (типа можно, но не для всех) :)

2020-03-30 03:45 UTC, merged